"""
Guardrails Module

Handles the pre-generation evidence gate and post-generation response
validation (Phase 8) — validation now checks the LLM's structured JSON
output (grounded / evidence_ids / confidence) rather than crude text
overlap.
"""

import asyncio
import json
import logging
from typing import List, Optional

import httpx

from .schemas import Evidence, GenerationResponse, GuardrailsResult
from config import settings
from retrieval.embeddings import embed_texts, EmbeddingError

logger = logging.getLogger(__name__)


class GuardrailsError(Exception):
    """Custom exception for guardrails errors."""
    pass


async def check_evidence(
    query: str,
    evidence: List[Evidence],
    min_confidence: Optional[float] = None,
    min_evidence_count: int = 1,
) -> GuardrailsResult:
    """
    Pre-generation gate: is there enough evidence to even attempt an answer?

    Args:
        query: user query (kept in the signature for logging/future use)
        evidence: fused Evidence list
        min_confidence: minimum normalized RRF score; defaults to
            settings.MIN_RETRIEVAL_SCORE
        min_evidence_count: minimum number of evidence items required

    Returns:
        GuardrailsResult with pass/fail status
    """
    min_confidence = settings.MIN_RETRIEVAL_SCORE if min_confidence is None else min_confidence

    try:
        issues = []

        if len(evidence) < min_evidence_count:
            issues.append(f"Insufficient evidence: only {len(evidence)} items found (need {min_evidence_count})")

        # Normalize RRF scores against the actual maximum a fused document
        # can reach (rank 1 in both Qdrant and BM25): 2 / (RRF_CONSTANT + 1).
        # An earlier version used a flat "score * 2" heuristic, which for
        # real RRF scores (~0.01-0.03) never got anywhere near a 0.3-0.5
        # threshold — it would have rejected even the best possible matches.
        max_possible_score = 2.0 / (settings.RRF_CONSTANT + 1)
        avg_score = sum(e.score for e in evidence) / len(evidence) if evidence else 0.0
        # Clamped on both ends, not just the upper one: this assumes every
        # evidence.score is on the small-positive RRF scale, which is true
        # for fused/qdrant/bm25 evidence, but a future evidence source with
        # a differently-scaled or negative score (a bug elsewhere, or a
        # feature not yet built) must degrade to a valid low-confidence
        # result here, never to a value QueryResponse's own [0,1]
        # validation would reject outright — a hard crash on the refusal
        # path is strictly worse than an honest "not confident" response.
        normalized_confidence = max(0.0, min(avg_score / max_possible_score, 1.0)) if max_possible_score > 0 else 0.0

        if normalized_confidence < min_confidence:
            issues.append(f"Low confidence: normalized score {normalized_confidence:.3f} below threshold {min_confidence}")

        passed = len(issues) == 0
        confidence = normalized_confidence if passed else (normalized_confidence * 0.5)

        return GuardrailsResult(
            passed=passed,
            confidence=confidence,
            reason="; ".join(issues) if issues else None,
            issues=issues,
        )

    except Exception as e:
        logger.error(f"Evidence gate check failed: {e}", exc_info=True)
        return GuardrailsResult(
            passed=False,
            confidence=0.0,
            reason=f"Guardrails error: {e}",
            issues=[f"Guardrails error: {e}"],
        )


_MODERATION_SYSTEM_PROMPT = """You are a content safety classifier. You will be shown one piece of text — an answer generated by a factual question-answering system. Decide whether it is unsafe.

Mark it unsafe ONLY if the text itself promotes, incites, endorses, or expresses hate speech, harassment, or discrimination against real people or groups, or provides actionable guidance intended to cause real-world harm. Do NOT mark it unsafe merely for factually describing or discussing historical violence, war, discrimination, or conflict in an informative, encyclopedic, or educational way — that is normal factual content, not unsafe content. When in doubt between "this is describing something" and "this is doing something," prefer describing (safe).

Respond with ONLY a single JSON object, nothing else: {"unsafe": true or false, "reason": "brief reason, or empty string if safe"}"""


async def _moderate_content(text: str) -> Optional[str]:
    """
    Roadmap Phase 23: replaces a fixed 5-keyword regex list (hate,
    violence, harass, abuse, discriminat) that was both trivially
    bypassable (no exact-word match required no flag) and prone to
    false-positiving on ordinary factual content (a history question
    mentioning "violence" would have tripped it). Uses a real LLM
    judgment call — the same "structured JSON, nothing else" pattern as
    pipeline/generation.py — to distinguish content that describes
    something harmful from content that actually does it.

    Returns None if the text is judged safe (or couldn't be checked at
    all), or a short human-readable reason string if flagged.

    Fails open (returns None — "not flagged") on any error reaching the
    moderation model, consistent with every other external check in this
    codebase (Qdrant, BM25, the reranker, and _groundedness_similarity
    above all degrade gracefully rather than take down an unrelated
    request over an external outage). This is deliberately a secondary,
    defense-in-depth layer, not the system's primary safety mechanism —
    the primary mechanism is that answers are constrained to retrieved,
    grounded evidence in the first place (see check_evidence and the
    groundedness check below).
    """
    if not text or not text.strip():
        return None

    api_key = settings.GROQ_API_KEY
    if not api_key:
        return None

    model = settings.GROQ_MODERATION_MODEL or settings.GROQ_LLM_MODEL
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": _MODERATION_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        "max_tokens": 100,
        "temperature": 0.0,
        "response_format": {"type": "json_object"},
    }
    timeout_s = settings.LLM_TIMEOUT_MS / 1000

    try:
        async with httpx.AsyncClient(timeout=timeout_s) as client:
            response = await client.post(url, headers=headers, json=payload)
        if response.status_code != 200:
            logger.warning(f"Moderation check returned {response.status_code}, treating as safe: {response.text}")
            return None

        data = json.loads(response.json()["choices"][0]["message"]["content"])
        if not isinstance(data, dict):
            return None
        if bool(data.get("unsafe", False)):
            return str(data.get("reason") or "flagged by content safety check")
        return None

    except (httpx.TimeoutException, httpx.TransportError) as e:
        logger.warning(f"Moderation check unreachable, treating as safe: {e}")
        return None
    except (json.JSONDecodeError, KeyError, IndexError, TypeError) as e:
        logger.warning(f"Moderation check returned unparseable output, treating as safe: {e}")
        return None


async def _groundedness_similarity(answer: str, cited_passages: List[str]) -> Optional[float]:
    """
    Cosine similarity between the generated answer and the passages it
    cited — an independent check on the LLM's own "grounded" self-report.
    Citation-ID validation (below) only proves the model cited a real
    passage; it says nothing about whether that passage actually supports
    what the model claimed. Embeddings are already normalized
    (retrieval/embeddings.py), so cosine similarity is just the dot product.

    Returns None (never fails validation) if there's nothing to compare, or
    if the embedding call itself fails — an embedding outage shouldn't take
    down answer validation on top of it.
    """
    if not cited_passages:
        return None
    try:
        vectors = await embed_texts([answer] + cited_passages)
    except EmbeddingError as e:
        logger.warning(f"Groundedness similarity check skipped (embedding failed): {e}")
        return None
    answer_vec, passage_vecs = vectors[0], vectors[1:]
    return max(sum(a * b for a, b in zip(answer_vec, pv)) for pv in passage_vecs)


async def validate_response(
    generation_result: GenerationResponse,
    evidence: List[Evidence],
) -> GuardrailsResult:
    """
    Post-generation gate: validates the LLM's structured output rather than
    doing word-overlap on free text.

    Args:
        generation_result: structured output from generation.generate_answer
        evidence: the fused Evidence actually retrieved for this query —
            used both to catch a hallucinated citation that slipped through
            generation's own filtering (defense in depth, not redundant
            paranoia — this function must be safe to call on its own) and
            to embed the cited passages for the groundedness check below.

    Returns:
        GuardrailsResult with validation status
    """
    try:
        issues = []
        valid_id_set = {e.document_id for e in evidence}
        passage_by_id = {e.document_id: e.passage for e in evidence}

        if not generation_result.answer or len(generation_result.answer.strip()) < 3:
            issues.append("Answer is too short or empty")

        if not generation_result.grounded:
            issues.append("Response is not marked as grounded in evidence")

        if not generation_result.evidence_ids:
            issues.append("No evidence_ids referenced")
        else:
            invalid_ids = [i for i in generation_result.evidence_ids if i not in valid_id_set]
            if invalid_ids:
                issues.append(f"References evidence_ids not in retrieved evidence: {invalid_ids}")

        # Launched before the groundedness embedding call below rather than
        # after, so the two independent external checks run concurrently —
        # the moderation call's latency is mostly hidden behind the
        # embedding call's instead of adding on top of it serially.
        moderation_task = asyncio.create_task(_moderate_content(generation_result.answer))

        similarity: Optional[float] = None
        if generation_result.evidence_ids:
            cited_passages = [passage_by_id[i] for i in generation_result.evidence_ids if i in passage_by_id]
            similarity = await _groundedness_similarity(generation_result.answer, cited_passages)
            if similarity is not None and similarity < settings.MIN_GROUNDEDNESS_SIMILARITY:
                issues.append(
                    f"Answer not semantically grounded in cited evidence "
                    f"(similarity={similarity:.3f} < {settings.MIN_GROUNDEDNESS_SIMILARITY})"
                )

        if not (0.0 <= generation_result.confidence <= 1.0):
            issues.append("Confidence out of range")

        moderation_reason = await moderation_task
        if moderation_reason:
            issues.append(f"Potentially unsafe content detected: {moderation_reason}")

        passed = len(issues) == 0

        return GuardrailsResult(
            passed=passed,
            confidence=generation_result.confidence if passed else 0.0,
            reason="; ".join(issues) if issues else "Response validated successfully",
            issues=issues,
            groundedness_similarity=similarity,
        )

    except Exception as e:
        logger.error(f"Response validation failed: {e}", exc_info=True)
        return GuardrailsResult(
            passed=False,
            confidence=0.0,
            reason=f"Validation error: {e}",
            issues=[f"Validation error: {e}"],
        )
